[project]
name = "flask_app"
version = "1.0.0"
description = "Backend for AIFlashcards website"
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
